"""Type contracts for desktop bootstrap and composition."""

from __future__ import annotations

from typing import Any, Protocol, Optional

from PyQt6.QtGui import QIcon


class UseCaseProtocol(Protocol):
    """Minimal use-case contract for DI container typing."""

    def execute(self, *args: Any, **kwargs: Any) -> Any: ...


class SessionManagerProtocol(Protocol):
    """Minimal session manager contract used by desktop bootstrap."""

    database_url: Optional[str]

    def create_tables(self) -> None: ...
    def close(self) -> None: ...


class DesktopContainerProtocol(Protocol):
    """Container contract required by desktop bootstrap."""

    def session_manager(self) -> SessionManagerProtocol: ...
    def add_transaction_use_case(self) -> UseCaseProtocol: ...
    def update_transaction_use_case(self) -> UseCaseProtocol: ...
    def delete_transaction_use_case(self) -> UseCaseProtocol: ...
    def get_transaction_use_case(self) -> UseCaseProtocol: ...
    def list_transactions_use_case(self) -> UseCaseProtocol: ...
    def search_transactions_use_case(self) -> UseCaseProtocol: ...
    def get_transaction_statistics_use_case(self) -> UseCaseProtocol: ...
    def add_counterparty_use_case(self) -> UseCaseProtocol: ...
    def update_counterparty_use_case(self) -> UseCaseProtocol: ...
    def delete_counterparty_use_case(self) -> UseCaseProtocol: ...
    def list_counterparties_use_case(self) -> UseCaseProtocol: ...
    def search_counterparties_use_case(self) -> UseCaseProtocol: ...
    def get_counterparty_statistics_use_case(self) -> UseCaseProtocol: ...


class MainWindowProtocol(Protocol):
    """Minimal main window contract used by desktop bootstrap."""

    def show(self) -> None: ...
    def refresh_data(self) -> None: ...


class TimerProtocol(Protocol):
    """Minimal timer contract used by desktop bootstrap."""

    def stop(self) -> None: ...


class QtApplicationProtocol(Protocol):
    """Minimal Qt application contract used by desktop bootstrap."""

    def setApplicationName(self, value: str) -> None: ...
    def setOrganizationName(self, value: str) -> None: ...
    def setOrganizationDomain(self, value: str) -> None: ...
    def setWindowIcon(self, icon: QIcon) -> None: ...
    def exec(self) -> int: ...
